### ISSUE TITLE
Why not using WM_TOUCH and WM_GESTURE?

### ISSUE THREAD

**Issue by DJm00n** [ichisadashioko/windows-touchpad#12]
Why you didn't use [WM_TOUCH](https://docs.microsoft.com/windows/win32/wintouch/wm-touchdown) and [WM_GESTURE](https://docs.microsoft.com/windows/win32/wintouch/wm-gesture) messages that are available since Windows 7?

[Sample code](https://github.com/microsoft/Windows-classic-samples/tree/main/Samples/Win7Samples/Touch/MTGestures/cpp).

**Comment by ichisadashioko** [comment]
I didn't know about it at all. I wonder if those messages is generated for touch screen devices. Thanks for pointing it out. I would love to experiment with it.

**Comment by DJm00n** [comment]
Just to add. For touch there seems a new [Pointer Input Messages and Notifications](https://docs.microsoft.com/en-us/windows/win32/inputmsg/wmpointer-reference) available since Windows 8: `WM_POINTERUPDATE`/`WM_POINTERDOWN`/`WM_POINTERUP` and [GetPointerType](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getpointertype) etc.
